name = "your-worker-name"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "fe1aaedd3eab92e69d17e708278d06db"

[vars]
ENVIRONMENT = "dev"
CACHE_ENABLED = "false"
CACHE_TTL = "300"
CACHE_TTL_M3U8 = "480"

# Production environment configuration
[env.production]
name = "your-worker-production"

[env.production.vars]
ENVIRONMENT = "production"
CACHE_ENABLED = "true"
CACHE_TTL = "1800"
CACHE_TTL_M3U8 = "480"

# Development environment configuration
[env.development]
name = "your-worker-dev"

[env.development.vars]
ENVIRONMENT = "dev"
CACHE_ENABLED = "false"
CACHE_TTL = "60"
CACHE_TTL_M3U8 = "0"